[package]
name = "iced_focus"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3.0"

[workspace]
members = [
    "iced_focus_derive",
    "examples/text_input",
]